project:
  type: website
  output-dir: docs

website:
  title: "Epidemiology"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - newpage.qmd
      - text: "More"
        menu:
          - talks.qmd
          - about.qmd 
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
  sidebar:
    style: "docked"
    search: true
    contents:
    - section: "Main"
      contents: 
      - index.qmd
    - section: "New"
      contents: 
      - newpage.qmd
    - section: "Others"
      contents: 
      - talks.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



